/// draw_text_outline(string,x,y,text_color,outline_color)

draw_set_color(argument4)
draw_text(argument1+1,argument2+1,argument0)
draw_text(argument1-1,argument2-1,argument0)
draw_text(argument1,argument2+1,argument0)
draw_text(argument1+1,argument2,argument0)
draw_text(argument1,argument2-1,argument0)
draw_text(argument1-1,argument2,argument0)
draw_text(argument1-1,argument2+1,argument0)
draw_text(argument1+1,argument2-1,argument0)
draw_set_color(argument3)
draw_text(argument1,argument2,argument0)
