/// status_ini()
var map = ds_map_create();
ds_map_add(map,"weather_dust",0);
ds_map_add(map,"weather_rain",0);
ds_map_add(map,"hunger_100",3200);
ds_map_add(map,"hunger_75",0);
ds_map_add(map,"hunger_50",0);
ds_map_add(map,"hunger_25",0);
ds_map_add(map,"hunger_10",0);
ds_map_add(map,"hunger_0",0);
ds_map_add(map,"thirst_100",3200);
ds_map_add(map,"thirst_75",0);
ds_map_add(map,"thirst_50",0);
ds_map_add(map,"thirst_25",0);
ds_map_add(map,"thirst_10",0);
ds_map_add(map,"thirst_0",0);
ds_map_add(map,"health_100",3200);
ds_map_add(map,"health_75",0);
ds_map_add(map,"health_50",0);
ds_map_add(map,"health_25",0);
ds_map_add(map,"health_10",0);
ds_map_add(map,"sanity_75",0);
ds_map_add(map,"sanity_50",0);
ds_map_add(map,"sanity_25",0);
ds_map_add(map,"sanity_10",0);
return map;
